openapi: 3.0.3
info:
  title: Individuals Savings Income (MTD)
  description: "The following groups of endpoints are stateful in the Sandbox\n* [UK\
    \ Savings Account](#tag/UK-Savings-Account)\n* [Savings Income](#tag/Savings-Income)\n\
    # Send fraud prevention data\nHMRC monitors transactions to help protect your\
    \ customers' confidential data from criminals and fraudsters. \n\n<div class=\"\
    govuk-warning-text warning-icon-fix\">\n  <span class=\"govuk-warning-text__icon\
    \ warning-icon-ui-fix\" aria-hidden=\"true\">!</span>\n  <strong class=\"govuk-warning-text__text\"\
    >\n    <span class=\"govuk-warning-text__assistive\">Warning</span>\n    You are\
    \ required by law to submit header data for this API. This includes all associated\
    \ APIs and endpoints.\n  </strong>\n</div>\n\n[Check the data you need to send](/guides/fraud-prevention/).\
    \ You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/1.0)\
    \ during initial development and as part of your quality assurance checks.\n\n\
    # Mapping APIs to Self Assessment tax return forms\nSome parameters in this API\
    \ map to box numbers in one or more Self Assessment tax return forms. To learn\
    \ more and to download this mapping information as a CSV file, go to [income-tax-mtd-changelog/mapping](https://github.com/hmrc/income-tax-mtd-changelog?tab=readme-ov-file#mapping-apis-to-self-assessment-tax-return-forms)\
    \ on GitHub.\n\n# Changelog\nYou can find the changelog in the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/#readme)\
    \ on GitHub.\n\n# Support\n\n* Direct reports of bugs or errors in Production\
    \ or Sandbox code, \nor queries about HMRC business functionality (such as how\
    \ a specific field is used by HMRC or why it is needed) to the [Software Development\
    \ Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).\n\
    * Send queries or feedback related to the design of the APIs (including recommended\
    \ changes) using\nthe [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues)\
    \ GitHub page.\n* <a href=\"/contact/report-technical-problem?newTab=true&service=api-documentation-frontend\"\
    \ target=\"_blank\">Is this page not working properly? (opens in new tab)</a>\n"
  version: "1.0"
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
tags:
- name: UK Savings Account
  description: Resources relating to an individual’s UK savings account
- name: Savings Income
  description: Resources relating to an individual's savings income
paths:
  /individuals/savings-income/uk-accounts/{nino}:
    get:
      summary: List All UK Savings Accounts
      parameters:
      - name: savingsAccountId
        in: query
        description: The unique identifier of a savings account.
        required: false
        schema:
          pattern: "^[A-Za-z0-9]{15}$"
          type: string
          example: SAVKB2UVwUTBQGJ
      security:
      - User-Restricted:
        - read:self-assessment
    post:
      summary: Add a UK Savings Account
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/savings-income/uk-accounts/{nino}/{taxYear}/{savingsId}:
    get:
      summary: Retrieve UK Savings Account Annual Summary
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend a UK Savings Account Annual Summary
      security:
      - User-Restricted:
        - write:self-assessment
  /individuals/savings-income/other/{nino}/{taxYear}:
    get:
      summary: Retrieve Savings Income
      security:
      - User-Restricted:
        - read:self-assessment
    put:
      summary: Create and Amend Savings Income
      security:
      - User-Restricted:
        - write:self-assessment
    delete:
      summary: Delete Savings Income
      security:
      - User-Restricted:
        - write:self-assessment
components:
  parameters:
    savingsAccountId:
      name: savingsAccountId
      in: query
      description: The unique identifier of a savings account.
      required: false
      schema:
        pattern: "^[A-Za-z0-9]{15}$"
        type: string
        example: SAVKB2UVwUTBQGJ
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)\
        \ API requests"
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access
